"""Ferramentas para chamar outros agentes"""

from langchain.tools import tool

from src.agents.data_analyst_agent import DataAnalystAgent
from src.agents.data_engineer import DataEngineerAgent
from src.agents.report_gen_agent import ReportGenAgent
from src.controllers.websocket_controller import manager
from src.data import StatusUpdate

_data_analyst = DataAnalystAgent()
_data_engineer = DataEngineerAgent()
_report_gen = ReportGenAgent()


async def update_agent_model(agent_name: str):
    """Função para atualizar o modelo de um agente após alteração nas configurações."""
    _data_analyst.initialize_agent()


async def _use_data_analyst(session_id: str, user_request: str) -> dict[str, str]:
    await manager.send_status_update(session_id, StatusUpdate.DATA_ANALYST_INIT)
    response = await _data_analyst.arun(user_request)

    return {'results': response['output']}


async def _use_data_engineer(session_id: str, user_request: str) -> dict[str, str]:
    await manager.send_status_update(session_id, StatusUpdate.DATA_ENGINEER_INIT)
    response = await _data_engineer.arun(user_request)

    return {'results': response['output']}


async def _use_report_gen(
    session_id: str, report_request: dict[str, str]
) -> dict[str, str]:
    report_request = dict(report_request)

    agent_input = (
        f'Report type: {report_request.get("report_type"), report_request},'
        f'Data and instructions: {report_request.get("data")}'
        f'Email (if available): {report_request.get("email")}'
    )

    await manager.send_status_update(session_id, StatusUpdate.REPORT_GEN_INIT)
    response = await _report_gen.arun(agent_input)

    return {'results': response['output']}


def create_agent_tools(session_id: str):
    """Método de fábrica para construção e injeção de dependências no contexto da ferramenta."""

    @tool('data_analyst')
    async def use_data_analyst(user_request: str):
        """This tool calls the Data Analyst to work on user's requests. The data and insights generated by the agent are returned. The Data Analyst has the following features:
        (create_bar_chart, create_histogram, create_line_plot, create_scatter_plot, detect_outliers_iqr, find_clusters_and_plot, get_correlation_matrix, get_data_summary, create_box_plot, create_correlation_heatmap, get_data_rows, get_metadata, python_ast_repl)
        These are the functions available for data analysis, the python_ast_repl function is powerful for creating insights not available in other functions.
        """

        return await _use_data_analyst(session_id, user_request)

    @tool('data_engineer')
    async def use_data_engineer(user_request: str):
        """This tool is used to call the Data Engineer to work on user's requests."""

        return await _use_data_engineer(session_id, user_request)

    @tool('report_gen')
    async def use_report_gen(report_request: dict[str, str]):
        """This tool is used to call the Report Generation agent to create and send report files to the user.
        The agent can: create reports as strings, transform the string in document files, and send the file to an email received from the user.
        To use this agent, you need to specify the type of report (analysis_results, validation_audit), the data to create reports about and a user email (if None was provided, ask if the user wants to send to an email or return directly).
        Parameter to receive: {'report_type': 'analysis_results', 'data': '...', 'email': 'user@email.com'}"""

        return await _use_report_gen(session_id, report_request)

    return [use_data_analyst, use_data_engineer, use_report_gen]
