"""Ferramentas para chamar outros agentes"""

import json

from langchain.tools import tool

from src.agents.base_agent import BaseAgent
from src.controllers.websocket_controller import manager
from src.data import StatusUpdate
from src.data.models import ModelTask


async def _use_data_analyst(
    _data_analyst: BaseAgent, session_id: str, user_request: str
) -> dict[str, str]:
    await manager.send_status_update(session_id, StatusUpdate.DATA_ANALYST_INIT)
    response = await _data_analyst.arun(user_request)

    return {'results': response['output']}


async def _use_data_engineer(
    _data_engineer: BaseAgent, session_id: str, user_request: str
) -> dict[str, str]:
    await manager.send_status_update(session_id, StatusUpdate.DATA_ENGINEER_INIT)
    response = await _data_engineer.arun(user_request)

    return {'results': response['output']}


async def _use_report_gen(
    _report_gen: BaseAgent, session_id: str, report_request: str
) -> dict[str, str]:
    try:
        report_request = json.load(report_request)

        agent_input = (
            f'Report type: {report_request.get("report_type")},'
            f'Data and instructions: {report_request.get("data")}'
        )
    except Exception:
        agent_input = report_request

    await manager.send_status_update(session_id, StatusUpdate.REPORT_GEN_INIT)
    response = await _report_gen.arun(agent_input)

    return {'results': response['output']}


def create_agent_tools(
    session_id: str,
    current_session: dict[str, BaseAgent | str],
):
    """Método de fábrica para construção e injeção de dependências no contexto da ferramenta."""
    _data_analyst = current_session.get(ModelTask.DATA_ANALYSIS)
    _data_engineer = current_session.get(ModelTask.DATA_TREATMENT)
    _report_gen = current_session.get(ModelTask.REPORT_GENERATION)

    @tool('data_analyst')
    async def use_data_analyst(user_request: str):
        """This tool calls the Data Analyst to work on user's requests. The data and insights generated by the agent are returned. The Data Analyst has the following features:
        bars chart generation, histogram chart generation, line plot generation, scatter plot generation, outliers detection with IQR, cluster locator and plot generation, correlation matrix generation, data summarize, box plot generation, correlation heatmap generation, get rows in data, python code tool for greater analysis).
        """
        if not _data_analyst:
            return 'Error: Data Analyst could not be initialized'

        return await _use_data_analyst(_data_analyst, session_id, user_request)

    @tool('data_engineer')
    async def use_data_engineer(user_request: str):
        """This tool is used to call the Data Engineer to work on user's requests, mostly about XML documents and tax documents. This agent is capable of extracting fields from text, perform data treatment and store the results in a Vector Store. It can also, extract from the Vector Store valid information and return it for analysis."""

        if not _data_engineer:
            return 'Error: Data Engineer could not be initialized'

        return await _use_data_engineer(_data_engineer, session_id, user_request)

    @tool('report_gen')
    async def use_report_gen(report_request: dict[str, str]):
        """This tool is used to call the Report Generation agent to create and send report files to the user.
        The agent can: create reports as strings, transform the string in document files, and send the file to an email received from the user.
        To use this agent, you need to specify the type of report (analysis_results, validation_audit) and the data to create reports about (results from previous tools and insights).
        Tool input received **should follow** the schema: {'report_type': 'analysis_results', 'data': '...'}, correctly escape the special characters inside the data or avoid using quotes."""

        if not _report_gen:
            return 'Error: Report Generator could not be initialized'

        return await _use_report_gen(_report_gen, session_id, report_request)

    return [use_data_analyst, use_data_engineer, use_report_gen]
